name: execute integration tasks

on:
  push:
    branches:
    - "**"

jobs:

  publish:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get version
        uses: hashibuto/actions/version@version-v0
        with:
          filename: VERSION

      - uses: hashibuto/actions/tagger@master
        with:
          create-version-tag: 'true'
